# ==============================================================================
# audit/scripts/03_WbHS.R
#
# Paper:
#   Gallego, Larroulet Philippi, and Repetto (2024)
#   "What's Behind Her Smile? Health, Looks, and Self-Esteem"
#
# MIS estimand audited here:
#   Table 5
#   First Follow-up
#   Full sample ("All")
#
# Outcome:
#   sd_rosen1
#
# Target coefficient:
#   treatment
#
# Preferred paper specification:
#   sd_rosen1 ~
#     treatment +
#     sd_rosen0 +
#     lb_years_education +
#     lb_jefe_hogar +
#     randomization-strata indicators
#
# Inference in the replication:
#   HC1 heteroskedasticity-robust standard errors.
#
# Important:
#   Robust covariance estimation does not alter the OLS coefficient itself.
#   Therefore the MIS search and exact point-estimate refits use the same OLS
#   regression specification.
#
# Current replication benchmark:
#   N = 634
#   beta(treatment) = 0.231708688059905
#
# MIS protocol:
#   k = 1, ..., floor(0.05 * N)
#   direction = coefficient increase and coefficient decrease
#   exact paper-estimator refit after every selected deletion set
#
# Data:
#   03_WbHS/data/processed/analysis_dataset.rds
#
# This is the analysis-ready dataset generated by the existing Paper 3
# replication workflow. Do NOT return to the six raw source datasets here.
# ==============================================================================


# ------------------------------------------------------------------------------
# 0. General options
# ------------------------------------------------------------------------------

options(
  stringsAsFactors = FALSE,
  scipen = 999
)


# ------------------------------------------------------------------------------
# 1. Locate repository
# ------------------------------------------------------------------------------

find_audit_root <- function() {
  
  # Normal case:
  # audit/audit.Rproj is open and this script is sourced from audit/.
  wd <- normalizePath(
    getwd(),
    winslash = "/",
    mustWork = TRUE
  )
  
  if (
    basename(wd) == "audit" &&
    dir.exists(file.path(wd, "function"))
  ) {
    return(wd)
  }
  
  
  # Otherwise infer location from the sourced script.
  script_file <- tryCatch(
    sys.frame(1)$ofile,
    error = function(e) NULL
  )
  
  if (!is.null(script_file)) {
    
    script_file <- normalizePath(
      script_file,
      winslash = "/",
      mustWork = TRUE
    )
    
    candidate <- dirname(
      dirname(script_file)
    )
    
    if (
      basename(candidate) == "audit" &&
      dir.exists(file.path(candidate, "function"))
    ) {
      return(candidate)
    }
  }
  
  
  stop(
    paste0(
      "Could not locate the audit project.\n",
      "Open audit/audit.Rproj and then run:\n",
      'source("scripts/03_WbHS.R")'
    ),
    call. = FALSE
  )
}


AUDIT_ROOT <- find_audit_root()


REPO_ROOT <- dirname(
  AUDIT_ROOT
)


PAPER_ROOT <- file.path(
  REPO_ROOT,
  "03_WbHS"
)


DATA_FILE <- file.path(
  PAPER_ROOT,
  "data",
  "processed",
  "analysis_dataset.rds"
)


OUTPUT_DIR <- file.path(
  AUDIT_ROOT,
  "output",
  "03_WbHS"
)


if (!dir.exists(PAPER_ROOT)) {
  
  stop(
    "Paper folder does not exist: ",
    PAPER_ROOT,
    call. = FALSE
  )
}


if (!file.exists(DATA_FILE)) {
  
  stop(
    paste0(
      "Required Paper 3 analysis-ready dataset does not exist:\n",
      DATA_FILE,
      "\n\n",
      "Run the Paper 3 replication first from 03_WbHS/:\n",
      'source("code/00_master.R")',
      "\n\n",
      "That workflow should generate:\n",
      "data/processed/analysis_dataset.rds"
    ),
    call. = FALSE
  )
}


# ------------------------------------------------------------------------------
# 2. Required packages
# ------------------------------------------------------------------------------

required_packages <- c(
  "ggplot2"
)


missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    logical(1),
    quietly = TRUE
  )
]


if (length(missing_packages) > 0L) {
  
  stop(
    paste0(
      "Install required package(s) first: ",
      paste(
        missing_packages,
        collapse = ", "
      )
    ),
    call. = FALSE
  )
}


# ------------------------------------------------------------------------------
# 3. Load shared MIS audit machinery
# ------------------------------------------------------------------------------

shared_files <- c(
  "dinkelbach_topk.R",
  "audit_validate.R",
  "audit_engine.R",
  "audit_output.R",
  "audit_plot.R"
)


for (f in shared_files) {
  
  path <- file.path(
    AUDIT_ROOT,
    "function",
    f
  )
  
  if (!file.exists(path)) {
    
    stop(
      "Missing shared audit file: ",
      path,
      call. = FALSE
    )
  }
  
  source(path)
}


# ------------------------------------------------------------------------------
# 4. Paper-specific constants
# ------------------------------------------------------------------------------

STUDY_ID <- "03_WbHS"


ESTIMAND_ID <- "table5_fu1_selfesteem_all"


TARGET <- "treatment"


EXPECTED_N <- 634L


EXPECTED_BETA <- 0.231708688059905


BETA_TOLERANCE <- 1e-8


MAX_REMOVAL_FRACTION <- 0.05


# ------------------------------------------------------------------------------
# 5. Load analysis-ready Paper 3 data
# ------------------------------------------------------------------------------

analysis_all <- readRDS(
  DATA_FILE
)


if (!is.data.frame(analysis_all)) {
  
  analysis_all <- as.data.frame(
    analysis_all
  )
}


# ------------------------------------------------------------------------------
# 6. Identify the paper's randomization-strata regressors
# ------------------------------------------------------------------------------

# This exactly follows the Paper 3 helper:
#
#   grep("^lb_estrato_level", names(data), value = TRUE)
#
# with lb_estrato_level4_1 omitted as the base indicator.
strata_vars <- grep(
  "^lb_estrato_level",
  names(analysis_all),
  value = TRUE
)


strata_vars <- setdiff(
  strata_vars,
  "lb_estrato_level4_1"
)


if (length(strata_vars) == 0L) {
  
  stop(
    paste0(
      "Could not find Paper 3 randomization-strata indicators.\n",
      "Expected variables beginning with `lb_estrato_level`."
    ),
    call. = FALSE
  )
}


message(
  "Paper 3 strata regressors found: ",
  length(strata_vars)
)


# ------------------------------------------------------------------------------
# 7. Check required variables
# ------------------------------------------------------------------------------

required_vars <- c(
  "ID_Participante",
  "sd_rosen1",
  "treatment",
  "sd_rosen0",
  "lb_years_education",
  "lb_jefe_hogar",
  strata_vars
)


missing_vars <- setdiff(
  required_vars,
  names(analysis_all)
)


if (length(missing_vars) > 0L) {
  
  stop(
    paste0(
      "Missing required Paper 3 variable(s): ",
      paste(
        missing_vars,
        collapse = ", "
      )
    ),
    call. = FALSE
  )
}


# ------------------------------------------------------------------------------
# 8. Permanent observation identifier
# ------------------------------------------------------------------------------

# ID_Participante is the participant identifier used throughout the original
# Paper 3 merge / replication workflow.
#
# Keep it unchanged so MIS row selections map back to the participant-level
# analysis data.
if (anyNA(analysis_all$ID_Participante)) {
  
  stop(
    "`ID_Participante` contains missing values in analysis_dataset.rds.",
    call. = FALSE
  )
}


if (anyDuplicated(analysis_all$ID_Participante)) {
  
  stop(
    "`ID_Participante` is not unique in analysis_dataset.rds.",
    call. = FALSE
  )
}


# ------------------------------------------------------------------------------
# 9. Define the exact published regression
# ------------------------------------------------------------------------------

# Paper 3 Table 5, first follow-up, self-esteem, full sample.
#
# main_outcome_block():
#
#   outcome  = sd_rosen1
#   baseline = sd_rosen0
#   controls = controls_unb()
#
# controls_unb():
#
#   lb_years_education
#   lb_jefe_hogar
#
# outcome_result() additionally includes the randomization-strata indicators.
rhs_vars <- c(
  TARGET,
  "sd_rosen0",
  "lb_years_education",
  "lb_jefe_hogar",
  strata_vars
)


original_formula <- stats::reformulate(
  termlabels = rhs_vars,
  response = "sd_rosen1"
)


# ------------------------------------------------------------------------------
# 10. Freeze the exact estimation sample
# ------------------------------------------------------------------------------

model_vars <- c(
  "sd_rosen1",
  rhs_vars
)


analysis_sample <- analysis_all[
  stats::complete.cases(
    analysis_all[
      ,
      model_vars,
      drop = FALSE
    ]
  ),
  ,
  drop = FALSE
]


row.names(analysis_sample) <- NULL


if (anyNA(analysis_sample$ID_Participante)) {
  
  stop(
    "`ID_Participante` contains missing values in the estimation sample.",
    call. = FALSE
  )
}


if (anyDuplicated(analysis_sample$ID_Participante)) {
  
  stop(
    "`ID_Participante` is not unique in the estimation sample.",
    call. = FALSE
  )
}


message(
  "Frozen Paper 3 estimation sample contains ",
  nrow(analysis_sample),
  " observations."
)


# ------------------------------------------------------------------------------
# 11. ORIGINAL REPLICATION
# ------------------------------------------------------------------------------

# The supplied replication fits this model using OLS and calculates HC1 robust
# standard errors afterward.
#
# HC1 affects inference, but does not change the OLS treatment slope.
original_fit <- stats::lm(
  formula = original_formula,
  data = analysis_sample,
  na.action = stats::na.fail
)


N_original <- as.integer(
  stats::nobs(original_fit)
)


original_coef <- stats::coef(
  original_fit
)


if (!TARGET %in% names(original_coef)) {
  
  stop(
    paste0(
      "Target coefficient `",
      TARGET,
      "` is absent from original_fit."
    ),
    call. = FALSE
  )
}


beta_original <- unname(
  original_coef[[TARGET]]
)


if (
  length(beta_original) != 1L ||
  !is.finite(beta_original)
) {
  
  stop(
    "Could not recover a finite Paper 3 treatment coefficient.",
    call. = FALSE
  )
}


# ------------------------------------------------------------------------------
# 12. Validate ORIGINAL REPLICATION
# ------------------------------------------------------------------------------

if (N_original != EXPECTED_N) {
  
  stop(
    paste0(
      "\n",
      "Folder:\n",
      "    audit/scripts/\n\n",
      
      "File:\n",
      "    03_WbHS.R\n\n",
      
      "Problem:\n",
      "    Original Paper 3 estimator does not reproduce expected N.\n\n",
      
      "Expected:\n",
      "    N = ", EXPECTED_N, "\n",
      "    beta = ",
      format(
        EXPECTED_BETA,
        digits = 16
      ),
      "\n\n",
      
      "Obtained:\n",
      "    N = ", N_original, "\n",
      "    beta = ",
      format(
        beta_original,
        digits = 16
      ),
      "\n\n",
      
      "Likely cause:\n",
      "    baseline/self-esteem controls, randomization strata, ",
      "missingness, or processed-data mismatch."
    ),
    call. = FALSE
  )
}


if (
  abs(
    beta_original -
    EXPECTED_BETA
  ) > BETA_TOLERANCE
) {
  
  stop(
    paste0(
      "\n",
      "Folder:\n",
      "    audit/scripts/\n\n",
      
      "File:\n",
      "    03_WbHS.R\n\n",
      
      "Problem:\n",
      "    Original Paper 3 estimator does not reproduce the retained ",
      "Table 5 treatment coefficient.\n\n",
      
      "Expected:\n",
      "    N = ", EXPECTED_N, "\n",
      "    beta = ",
      format(
        EXPECTED_BETA,
        digits = 16
      ),
      "\n\n",
      
      "Obtained:\n",
      "    N = ", N_original, "\n",
      "    beta = ",
      format(
        beta_original,
        digits = 16
      ),
      "\n",
      
      "    absolute difference = ",
      format(
        abs(
          beta_original -
            EXPECTED_BETA
        ),
        scientific = TRUE
      ),
      "\n\n",
      
      "Likely cause:\n",
      "    treatment / baseline Rosenberg / controls / strata ",
      "specification mismatch."
    ),
    call. = FALSE
  )
}


message(
  "Original Paper 3 replication check PASSED."
)


message(
  "N_original = ",
  N_original
)


message(
  "beta_original = ",
  format(
    beta_original,
    digits = 16
  )
)


# ------------------------------------------------------------------------------
# 13. MIS-compatible OLS representation
# ------------------------------------------------------------------------------

# Unlike Papers 1 and 2, no absorbed fixed-effect conversion is necessary here.
#
# The published Paper 3 point estimator is already ordinary least squares with
# explicit randomization-strata indicators.
mis_formula <- original_formula


mis_fit <- stats::lm(
  formula = mis_formula,
  data = analysis_sample,
  na.action = stats::na.fail
)


N_mis <- as.integer(
  stats::nobs(mis_fit)
)


mis_coef <- stats::coef(
  mis_fit
)


if (!TARGET %in% names(mis_coef)) {
  
  stop(
    paste0(
      "Target coefficient `",
      TARGET,
      "` is absent from mis_fit."
    ),
    call. = FALSE
  )
}


beta_mis <- unname(
  mis_coef[[TARGET]]
)


# ------------------------------------------------------------------------------
# 14. Baseline MIS validation
# ------------------------------------------------------------------------------

if (N_mis != N_original) {
  
  stop(
    paste0(
      "\n",
      "Folder:\n",
      "    audit/scripts/\n\n",
      
      "File:\n",
      "    03_WbHS.R\n\n",
      
      "Problem:\n",
      "    MIS-compatible OLS does not use the original estimator's N.\n\n",
      
      "Expected:\n",
      "    N = ", N_original, "\n\n",
      
      "Obtained:\n",
      "    N = ", N_mis, "\n\n",
      
      "Likely cause:\n",
      "    sample or formula mismatch."
    ),
    call. = FALSE
  )
}


if (
  !is.finite(beta_mis) ||
  abs(
    beta_mis -
    beta_original
  ) > BETA_TOLERANCE
) {
  
  stop(
    paste0(
      "\n",
      "Folder:\n",
      "    audit/scripts/\n\n",
      
      "File:\n",
      "    03_WbHS.R\n\n",
      
      "Problem:\n",
      "    MIS-compatible OLS does not reproduce the original treatment slope.\n\n",
      
      "Expected:\n",
      "    beta = ",
      format(
        beta_original,
        digits = 16
      ),
      "\n\n",
      
      "Obtained:\n",
      "    beta = ",
      format(
        beta_mis,
        digits = 16
      ),
      "\n",
      
      "    absolute difference = ",
      format(
        abs(
          beta_mis -
            beta_original
        ),
        scientific = TRUE
      )
    ),
    call. = FALSE
  )
}


# ------------------------------------------------------------------------------
# 15. Required full-rank check
# ------------------------------------------------------------------------------

X_mis <- stats::model.matrix(
  mis_fit
)


rank_mis <- qr(
  X_mis
)$rank


if (rank_mis < ncol(X_mis)) {
  
  stop(
    paste0(
      "\n",
      "Folder:\n",
      "    audit/scripts/\n\n",
      
      "File:\n",
      "    03_WbHS.R\n\n",
      
      "Problem:\n",
      "    MIS model matrix is rank deficient.\n\n",
      
      "Rank:\n",
      "    ", rank_mis, "\n\n",
      
      "Columns:\n",
      "    ", ncol(X_mis), "\n\n",
      
      "Required action:\n",
      "    Inspect which randomization-strata nuisance column is aliased ",
      "before running MIS. Do not silently drop observations."
    ),
    call. = FALSE
  )
}


message(
  "Baseline MIS validation PASSED."
)


message(
  "N_mis = ",
  N_mis
)


message(
  "beta_mis = ",
  format(
    beta_mis,
    digits = 16
  )
)


message(
  "absolute beta difference = ",
  format(
    abs(
      beta_mis -
        beta_original
    ),
    scientific = TRUE
  )
)


message(
  "MIS model matrix rank = ",
  rank_mis,
  " / ",
  ncol(X_mis)
)


# ------------------------------------------------------------------------------
# 16. Original-estimator function for EXACT REFITS
# ------------------------------------------------------------------------------

paper_refit <- function(
    data,
    spec
) {
  
  # Exact Paper 3 point-estimator refit.
  #
  # The original reporting step applies HC1 covariance to this lm object,
  # but HC1 does not change coef(fit)["treatment"].
  stats::lm(
    formula = original_formula,
    data = data,
    na.action = stats::na.fail
  )
}


# ------------------------------------------------------------------------------
# 17. Define MIS audit specification
# ------------------------------------------------------------------------------

spec <- audit_spec(
  study_id = STUDY_ID,
  
  estimand_id = ESTIMAND_ID,
  
  data = analysis_sample,
  
  mis_formula = mis_formula,
  
  target = TARGET,
  
  id_var = "ID_Participante",
  
  refit_fn = paper_refit,
  
  refit_target = TARGET,
  
  expected_beta = EXPECTED_BETA,
  
  expected_n = EXPECTED_N,
  
  beta_tolerance = BETA_TOLERANCE,
  
  # Explicitly enforce the empirical-audit instruction:
  # k = 1, ..., floor(0.05 * N)
  max_fraction = MAX_REMOVAL_FRACTION
)


# ------------------------------------------------------------------------------
# 18. MIS SEARCH + EXACT REFIT
# ------------------------------------------------------------------------------

audit_result <- run_mis_audit(
  spec = spec,
  verbose = TRUE
)


# ------------------------------------------------------------------------------
# 19. Add standardized instruction-compatible aliases
# ------------------------------------------------------------------------------

# Keep shared-engine internal fields but add the standardized names required by
# the empirical MIS audit instruction.

audit_result$path$N <- EXPECTED_N


audit_result$path$beta_after <-
  audit_result$path$beta_mis


audit_result$path$delta_beta <-
  audit_result$path$delta_mis


audit_result$path$abs_delta_beta <-
  audit_result$path$abs_delta_mis


audit_result$path$relative_change <-
  audit_result$path$relative_change_mis


audit_result$path$nested <-
  audit_result$path$nested_mis


audit_result$path$valid_refit <-
  audit_result$path$valid_mis


audit_result$path$refit_error <-
  audit_result$path$refit_error_mis


# Baseline aliases.
audit_result$baseline$N <-
  audit_result$baseline$n


audit_result$baseline$max_k <-
  max(
    audit_result$path$k,
    na.rm = TRUE
  )


audit_result$baseline$max_removal_fraction <-
  max(
    audit_result$path$removal_fraction,
    na.rm = TRUE
  )


# Summary alias.
audit_result$summary$N <-
  audit_result$summary$n


# ------------------------------------------------------------------------------
# 20. Save standardized outputs
# ------------------------------------------------------------------------------

dir.create(
  OUTPUT_DIR,
  recursive = TRUE,
  showWarnings = FALSE
)


saved_files <- save_mis_audit(
  audit = audit_result,
  output_dir = OUTPUT_DIR,
  prefix = "audit"
)


# ------------------------------------------------------------------------------
# 21. Ensure influential-ID output contains model_row_position
# ------------------------------------------------------------------------------

ids_file <- saved_files$influential_ids


ids_output <- utils::read.csv(
  ids_file,
  stringsAsFactors = FALSE,
  check.names = FALSE
)


if (
  "position" %in% names(ids_output) &&
  !"model_row_position" %in% names(ids_output)
) {
  
  ids_output$model_row_position <-
    ids_output$position
}


utils::write.csv(
  ids_output,
  ids_file,
  row.names = FALSE,
  na = ""
)


# ------------------------------------------------------------------------------
# 22. Standard MIS figure
# ------------------------------------------------------------------------------

plot_mis_audit(
  audit = audit_result,
  
  output_file = file.path(
    OUTPUT_DIR,
    "fig_mis_audit.pdf"
  ),
  
  title = paste0(
    "Gallego et al. (2024): Self-Esteem — Treatment"
  )
)


# ------------------------------------------------------------------------------
# 23. Final console report
# ------------------------------------------------------------------------------

message("")
message("============================================================")
message("Paper 3 MIS audit complete")
message("============================================================")


message(
  "Study: ",
  STUDY_ID
)


message(
  "Estimand: ",
  ESTIMAND_ID
)


message(
  "Outcome: sd_rosen1"
)


message(
  "Target: ",
  TARGET
)


message(
  "N: ",
  EXPECTED_N
)


message(
  "Original beta: ",
  format(
    beta_original,
    digits = 16
  )
)


message(
  "MIS-compatible beta: ",
  format(
    beta_mis,
    digits = 16
  )
)


message(
  "MIS/original absolute difference: ",
  format(
    abs(
      beta_mis -
        beta_original
    ),
    scientific = TRUE
  )
)


message(
  "Maximum k audited: ",
  max(
    audit_result$path$k,
    na.rm = TRUE
  )
)


message(
  "Maximum removal fraction: ",
  format(
    max(
      audit_result$path$removal_fraction,
      na.rm = TRUE
    ),
    digits = 6
  )
)


message(
  "Output folder: ",
  OUTPUT_DIR
)


message("")


print(
  audit_result$baseline
)


print(
  audit_result$summary
)