# 00_run_all.R
# Master runner for the Huguka Dukore R replication.
# Run from the repository root: source("code/00_run_all.R")
rm(list=ls())

source("code/01_setup.R")
source("code/02_variable_lists.R")
source("code/03_helpers.R")

message("[04] Covariate choice")
source("code/04_covariate_choice.R")
message("[05] Attrition")
source("code/05_attrition.R")
message("[06] Balance")
source("code/06_balance.R")
message("[07] HD uptake")
source("code/07_hd_uptake.R")
message("[08] ITT")
source("code/08_itt.R")
message("[09] ITT employment deconstruction")
source("code/09_itt_employment_deconstruction.R")
message("[10] Cost-equivalent analysis")
source("code/10_cost_equivalent.R")
message("[11] Cost-equivalent linearity")
source("code/11_cost_equivalent_linearity.R")
message("[12] Complementarities")
source("code/12_complementarities.R")
message("[13] Heterogeneity")
source("code/13_heterogeneity.R")
message("[14] Spillovers")
source("code/14_spillovers.R")
message("[15] Cash accounting")
source("code/15_cash_accounting.R")

message("Replication scripts completed.")
